server:
  port: 8086

spring:
  application:
    name: MATCHING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/matching_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

routing:
  osrm:
    base-url: ${ROUTING_OSRM_BASE_URL:http://osrm:5000}
